[build]
  base = "client/dist"  # Specify the correct base directory here
  command = "npm run build"  # Your build command
  publish = "client/dist"  # Directory to deploy

[build.environment]
  NODE_VERSION = "14"  # Example of environment variable

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

