# netlify.toml

# Build settings
[build]
  # Directory to change to before starting a build
  base = "client"
  # Build command to run (assuming your project uses npm)
  command = "npm run build"
  # Directory that should be deployed
  publish = "client/dist"
  environment = { NODE_ENV = "production" }

# Redirects settings
[[redirects]]
  # Redirect all requests to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for build
[build.environment]
  # Specify the Node.js version (adjust according to your project's requirements)
  NODE_VERSION = "14"
  node_modules/vite = "*"

# Production environment variables
[context.production.environment]
  # Set NODE_ENV to production
  NODE_ENV = "production"

# Development environment variables (if needed)
[context.development.environment]
  # Set NODE_ENV to development
  NODE_ENV = "development"
