# netlify.toml

[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14"
  node_modules/vite = "*"

[context.production.environment]
  NODE_ENV = "production"

[context.development.environment]
  NODE_ENV = "development"
