[build]
  base = "client/dist"  # Replace with your base directory path
  command = "npm run build"  # Command to build your project
  publish = "client/dist"  # Directory to deploy

[build.environment]
  NODE_VERSION = "14"  # Example of setting an environment variable

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
